apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - go-deployment.yml
  - go-service.yml
  - node-deployment.yml
  - node-service.yml
  - loadbalancer.yml

commonLabels:
  environment: base
  project: monorepo
