apiVersion: v1
kind: Service
metadata:
  name: go-service-lb
spec:
  type: LoadBalancer
  selector:
    app: go-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-service-lb
spec:
  type: LoadBalancer
  selector:
    app: node-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
