apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  selector:
    app: node-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP