apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yml

commonLabels:
  environment: production

images:
- name: registry.digitalocean.com/cfx/go-service
  newName: registry.digitalocean.com/cfx/go-service
  newTag: latest
- name: registry.digitalocean.com/cfx/node-service
  newName: registry.digitalocean.com/cfx/node-service
  newTag: latest
