apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  -../../base

patchesStrategicMerge:
  - replica-patch.yml

# This section is updated by the CI/CD pipeline
images:
- name: your-registry/go-service
  newName: your-registry/go-service
  newTag: latest
- name: your-registry/node-service
  newName: your-registry/node-service
  newTag: latest