apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yml

commonLabels:
  environment: production

# Image tags will be updated by CI/CD pipeline
images:
- name: registry.digitalocean.com/monorepo-registry/go-service
  newName: registry.digitalocean.com/monorepo-registry/go-service
  newTag: latest
- name: registry.digitalocean.com/monorepo-registry/node-service
  newName: registry.digitalocean.com/monorepo-registry/node-service
  newTag: latest